# Generated by Django 5.1.3 on 2024-11-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=400, verbose_name='Full name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
