# Generated by Django 5.1.3 on 2024-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=255)),
                ('short_name', models.CharField(verbose_name=10)),
            ],
        ),
    ]
