# Generated by Django 5.1.3 on 2024-11-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
    ]
